### ISSUE TITLE
Subroutine data check not persistent

### ISSUE THREAD

**Issue by Ovid** [Perl-Oshun/oshun#1]
If I run this:

```perl
my $size :of(UINT) = 3;
$size = -2.43;
```

That fails with `Can't assign -2.43 to $size: failed UINT check at ...`

However, if I run this:

```perl
sub foo ( $max_size :of(UINT) ) {
    say "Max size is $max_size";
    $max_size = -2.43;
    say "Max size is $max_size";
}

foo(3);
foo(-42);
```

That prints:

```
Max size is 3
Max size is -2.43
Can't pass -42 to parameter $max_size in call to foo() at ...
```
So the check works when you make the sub call, but no longer applies within the body of the subroutine.

This is for version 0.00001.

**Comment by zmughal** [comment]
> ```perl
>         &Variable::Magic::cast(\$max_size, $Data::Checks::Parser::SCALAR_WIZARD_FOR{'$max_size/UINT'});
> ```

Looking at the deparse, is it the case that this `cast()` call should be inside of the `__IMPL__` sub right before the block? My reasoning:

> ```perl
> sub foo ($max_size) {
>     state sub __IMPL__ ($max_size) {
> ```

I believe that the magic is being associated with the `$max_size` in the parameter list for the outer `sub foo` and not with the `$max_size` for the inner `sub __IMPL__`.

I made a quick and dirty change to just copy `$OF_CHECKS` to right before the `«block»` here

https://github.com/Perl-Oshun/oshun/blob/b83ae9e973c6bdef9468b758d896d0ac92792b7a/lib/Data/Checks/Parser.pm#L1460-L1467

and that gives the expected exception:

```
Max size is 3
Can't assign -2.43 to $max_size: failed UINT check at ...
```

Maybe the check of the parameter before the call can be split from the call to `Variable::Magic::cast` so that it is only checked once.

**Comment by Ovid** [comment]
@zmughal Would you be so kind as to give me a code review? https://github.com/Perl-Oshun/oshun/pull/31

**Comment by Ovid** [comment]
Wait, I see you already have a PR. Sorry for that!

**Comment by Ovid** [comment]
Thanks for the PR. It's now merged. Looking forward to the CI one being resolved.

I also have a trivial PR at https://github.com/Perl-Oshun/oshun/pull/32
