### ISSUE TITLE
Would be a mistake to allow an INT to be both "0" and 0?

### ISSUE THREAD

**Issue by jhthorsen** [Perl-Oshun/oshun#33]
```perl
my $age :of(INT) = 42; # ok
my $age :of(INT) = "42"; # not cool
```

I haven't poked inside the compiler, but I was wondering if Perl could get optimized in the future if a SV was indeed an IV or PV at compile time, and not changeable.

I also think it would also be nice if a function that convert from Perl to JSON knew for sure what something was, since it was defined by the programmer, and not by accident.

**Comment by Ovid** [comment]
One of several problems with coercions is this:

```perl
my $age :of(INT) = \@array;
```

That could coerce in a very large integer and almost certainly not the value that you want. I could see revisiting this post-MVP (and probably long before experimental status is removed), but for now, what's the simplest, most correct thing that we can get working?

You, however, can safely experiment with it (once we get [coercions](https://github.com/Perl-Oshun/oshun/wiki/Initial-Specification#coercions) working):

```perl
coercion MyInt :to(INT) ($n) {
    my $int = int($n); 
    die "$n can't be converted to an integer"  if !looks_like_number($n) || ( $int != $n );
    return $int;
}
```

**Comment by jhthorsen** [comment]
How about disabling coercion and just have strict types? Does that would imply a completely different language..? If so, then please close this issue as "Won't fix", or something similar.

When it comes to your example above, I would expect that assigning an array-ref to an INT should result in a compile time error. If that is impossible, then it sounds like the proposed type-checking will have a runtime cost which will slow down programs, instead of helping editors (LSP-integrations?) and developers to do the right thing when writing the code, and also making it impossible to do compile time speedups.

**Comment by Ovid** [comment]
A few comments.

First, we call these "checks", not "types." That's because many developers get very upset if a "type" system doesn't match their personal expectations. In fact, data checks don't match what I want (long story), but it's a reasonable enough compromise based on Perl prior art that I feel OK with them. But if we call them "types," there's a subset of developers who get very mad. We'd like to avoid mad :)

It's entirely possibly that coercions won't make it into Oshun. We don't yet know. They are problematic in several ways. However, for downgrading checks to warnings or disabling them entirely, we can't do that with coercions because coercions wind up being this weird "action at a distance" which will cause code to break if they're disabled.

Also, for the MVP, we do not handle compile-time checks. We'd simply like to see what people do with them. Once we have a better idea of real-world usage, we can start taking the next steps. Oshun is very much a "lean" project in this respect. "Make the smallest thing that can possibly work and only iterate on top of that if successful."

Thus, you're correct there will be a runtime cost. The extreme late-binding of Perl often means that in many cases, it's _impossible_ to know at compile time what kinds of checks apply.

**Comment by jhthorsen** [comment]
Thank you for your explanation.

**Comment by Ovid** [comment]
You're very welcome. Sorry it's not the answers you're looking for!
